Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
scot_sm_uot = SinkhornSolver(nits_uot=1)
pi_samp_sm_uot, pi_feat_sm_uot = scot_sm_uot.coot(X, y, eps=1e-3, verbose=True)
------------------

----- stdout -----
BCD Iteration 1 - Loss: 0.106227, 0.109635
BCD Iteration 2 - Loss: 0.082098, 0.086200
BCD Iteration 3 - Loss: 0.087553, 0.091607
BCD Iteration 4 - Loss: 0.091136, 0.095348
BCD Iteration 5 - Loss: 0.088741, 0.092886
BCD Iteration 6 - Loss: 0.100078, 0.104104
BCD Iteration 7 - Loss: 0.090849, 0.094953
BCD Iteration 8 - Loss: 0.085977, 0.090044
BCD Iteration 9 - Loss: 0.078745, 0.082966
BCD Iteration 10 - Loss: 0.074906, 0.079070
BCD Iteration 11 - Loss: 0.072437, 0.076522
BCD Iteration 12 - Loss: 0.070589, 0.074822
BCD Iteration 13 - Loss: 0.065982, 0.070086
BCD Iteration 14 - Loss: 0.079741, 0.083870
BCD Iteration 15 - Loss: 0.076966, 0.081101
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[2], line 2[0m
[1;32m      1[0m scot_sm_uot [38;5;241m=[39m SinkhornSolver(nits_uot[38;5;241m=[39m[38;5;241m1[39m)
[0;32m----> 2[0m pi_samp_sm_uot, pi_feat_sm_uot [38;5;241m=[39m scot_sm_uot[38;5;241m.[39mcoot(X, y, eps[38;5;241m=[39m[38;5;241m1e-3[39m, verbose[38;5;241m=[39m[38;5;28;01mTrue[39;00m)

[0;31mValueError[0m: too many values to unpack (expected 2)

